name: base_kits
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_analytics: ^10.5.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  firebase_storage: ^11.6.9

  in_app_purchase: ^3.1.11
  rxdart: ^0.27.7
  path_provider: ^2.0.11
  shared_preferences: ^2.0.18
  json_annotation: ^4.4.0
  connectivity_plus: ^3.0.3
  in_app_review: ^2.0.6
  flutter_email_sender: ^5.2.0
  google_mobile_ads: ^3.0.0
  package_info_plus: ^4.0.2
  device_info_plus: ^8.2.2
  number_display: ^3.0.0
  package_info: ^2.0.2
  auto_size_text: ^3.0.0
  lit_relative_date_time: ^1.2.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
